### ISSUE TITLE
__contains__ method generated once per field

### ISSUE THREAD

**Issue by schmichael** [bumptech/palm#9]
Given `t.proto`:

```
message A {
  optional string foo = 0;
}
```

`grep -c __contains__ t_palm.py => 1`

Which is what you expect.

However, add a couple more fields:

```
message A {
  optional string foo = 0;
  optional string bar = 1;
  optional string baz = 2;
}
```

And you get `__contains__` defined 3 times: `grep -c __contains__ t_palm.py => 3`

The definition is the same, so this is a harmless bug other than a few extra instructions processed when Python compiles the proto's class.

**Comment by jamwt** [comment]
Roger, yep, mistake.  Thanks for the report.  Pull request?  :-)

**Comment by schmichael** [comment]
I think this was fixed in: https://github.com/bumptech/palm/commit/4818942ad410c498b2811a7cfab851026c811be5
